name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    
    - name: prepare curl
      run:  sudo apt-get install libcurl4-openssl-dev
      shell: bash

    - name: prepare libcheck
      run:  sudo apt-get install check
      shell: bash    
      
    - name: make tests
      run:  make tests
      
    - name: run
      run:  ./build/tests/boattest
